"""
@Author : Manish Devgan
@Github : https://github.com/gabru-md
@Language : Python 2.7
"""
import sys
from nsitbot import NSITBot

"""
NSITBot example to generate responses for 
'BOT' and 'HELLO' type of messages using 
bot.generateResponse() and bot.predict()
"""

bot = NSITBot(
    name="My First Bot",
    owner="Manish Devgan",
    version="0.0.1" 
)

incoming_message = str(raw_input("Message: "))

response = bot.generateResponse(bot.predict(incoming_message))

"""
bot.generateResponse ,as the name suggests,
generates responses for the prediction that is 
generated by bot.predict()

bot.generateResponse() takes a list as argument
that contains [message_in_lower_case,prediction]
and bot.predict() returns the list containing
the elements in exact same format as required/


Therefore the best possible way to call it is:
    bot.generateResponse(bot.predict(TEXT_TO_PREDICT))
"""
print "The response to: '" + str(incoming_message) + "' is: '" + response + "'"
